config/routes.rb
Rails.application.routes.draw do

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list


  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :guid

  def guid
    # only if it doesn't exist already?
    if session[:guid].blank?
      session[:guid] = SecureRandom.urlsafe_base64
    end
    return session[:guid]
  end

  def append_info_to_payload(payload)
    super
    payload[:host] = request.host
    payload[:guid] = guid
    payload[:env] = Rails.env.to_s
    payload[:level] = Rails.logger.level

  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo_list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "Todo item completed"
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo List</title>

  <!-- Always force latest IE rendering engine or request Chrome Frame -->
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <meta name="viewport" content="width=device-width">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

 <header class="site-header">
  <nav class="site-nav container" role="navigation">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-list" aria-hidden="true"></i> Todo List
      <% end %>
<!--
      <ul class="nav-links">
        <li><%= link_to 'Home', root_path %>
          <ul></ul>
        </li>
      </ul>
      </div>
      <div class="mobile-menu"><i class="fa fa-navicon"></i></div>

    </nav>
-->
  </div>
</header>

<main class="site-main">
  <div class="container module">
    <div class="container-wrapper">
      <%= yield %>
    </div>
  </div>
</main>

<footer class="site-footer">
  <div class="container">
    <p>&copy; <%= Time.now.year %> <a href="#">Todo list</a></p>
  </div>
</footer>

  <!-- bottom  -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :js %>
  <% if Rails.env == "Production" %><!-- ex. google analytics --><% end %>
  <!-- /bottom  -->
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Task" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
  <% if todo_item.completed? %>
    <div class="complete">
      <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="todo_taks">
      <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
        <i class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="todo_taks">
      <p><%= todo_item.content %></p>
    </div>
    <div class="trash">
      <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
    <p class="todo_list_sub_title"><%= todo_list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New List", new_todo_list_path %>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">Todo List</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div id="todo_items_wrapper">
  <%= render @todo_list.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
  <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }
 %> |
  <%= link_to 'Back', todo_lists_path %>
</div>

app/views/welcome/index.html.erb
<h1>Todo list</h1>